language: python
python:
  - 3.5
sudo: true
cache:
  directories:
  - $HOME/.pip/wheels
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
  matrix:
    - ENV: 2.7-fnaccents-pnaccents-no-django
    - ENV: 2.7-fnaccents-pnaccents-no-nodj
    - ENV: 2.7-fndef-pndef-argparse-django
    - ENV: 2.7-fndef-pndef-argparse-nodj
    - ENV: 2.7-fndef-pndef-click-django
    - ENV: 2.7-fndef-pndef-click-nodj
    - ENV: 2.7-fndef-pndef-no-django
    - ENV: 2.7-fndef-pndef-no-nodj
    - ENV: 2.7-fndef-pndef-plain-django
    - ENV: 2.7-fndef-pndef-plain-nodj
    - ENV: 2.7-fndef-pnquotes-no-django
    - ENV: 2.7-fndef-pnquotes-no-nodj
    - ENV: 2.7-fnquotes-pndef-no-django
    - ENV: 2.7-fnquotes-pndef-no-nodj
    - ENV: 2.7-fnquotes-pnquotes-no-django
    - ENV: 2.7-fnquotes-pnquotes-no-nodj
    - ENV: 3.4-fnaccents-pnaccents-no-django
    - ENV: 3.4-fnaccents-pnaccents-no-nodj
    - ENV: 3.4-fndef-pndef-argparse-django
    - ENV: 3.4-fndef-pndef-argparse-nodj
    - ENV: 3.4-fndef-pndef-click-django
    - ENV: 3.4-fndef-pndef-click-nodj
    - ENV: 3.4-fndef-pndef-no-django
    - ENV: 3.4-fndef-pndef-no-nodj
    - ENV: 3.4-fndef-pndef-plain-django
    - ENV: 3.4-fndef-pndef-plain-nodj
    - ENV: 3.4-fndef-pnquotes-no-django
    - ENV: 3.4-fndef-pnquotes-no-nodj
    - ENV: 3.4-fnquotes-pndef-no-django
    - ENV: 3.4-fnquotes-pndef-no-nodj
    - ENV: 3.4-fnquotes-pnquotes-no-django
    - ENV: 3.4-fnquotes-pnquotes-no-nodj
    - ENV: 3.5-fnaccents-pnaccents-no-django
    - ENV: 3.5-fnaccents-pnaccents-no-nodj
    - ENV: 3.5-fndef-pndef-argparse-django
    - ENV: 3.5-fndef-pndef-argparse-nodj
    - ENV: 3.5-fndef-pndef-click-django
    - ENV: 3.5-fndef-pndef-click-nodj
    - ENV: 3.5-fndef-pndef-no-django
    - ENV: 3.5-fndef-pndef-no-nodj
    - ENV: 3.5-fndef-pndef-plain-django
    - ENV: 3.5-fndef-pndef-plain-nodj
    - ENV: 3.5-fndef-pnquotes-no-django
    - ENV: 3.5-fndef-pnquotes-no-nodj
    - ENV: 3.5-fnquotes-pndef-no-django
    - ENV: 3.5-fnquotes-pndef-no-nodj
    - ENV: 3.5-fnquotes-pnquotes-no-django
    - ENV: 3.5-fnquotes-pnquotes-no-nodj
before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
  - sudo apt-get install enchant
install:
  - mkdir -p ~/.pip
  - cp ci/pip.conf ~/.pip/pip.conf
  - pip install -U wheel setuptools
  - pip wheel tox virtualenv cookiecutter bumpversion
  - pip wheel pytest-capturelog pytest-cov pytest
  - pip wheel nose coverage
  - pip wheel cpp-coveralls
  - pip wheel jinja2 matrix
  - pip wheel docutils check-manifest flake8 readme-renderer pygments
  - pip install -I -U tox cookiecutter bumpversion
script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - ci/test.sh $ENV
notifications:
  email:
    on_success: never
    on_failure: always
