language: python
python:
  - 3.5
cache: pip
jobs:
  include:
    - ENV: fnaccents-pnaccents-no-django
    - ENV: fnaccents-pnaccents-no-nodj
    - ENV: fndef-pndef-argparse-django
    - ENV: fndef-pndef-argparse-nodj
    - ENV: fndef-pndef-click-django
    - ENV: fndef-pndef-click-nodj
    - ENV: fndef-pndef-no-django
    - ENV: fndef-pndef-no-nodj
    - ENV: fndef-pndef-plain-django
    - ENV: fndef-pndef-plain-nodj
    - ENV: fndef-pnquotes-no-django
    - ENV: fndef-pnquotes-no-nodj
    - ENV: fnquotes-pndef-no-django
    - ENV: fnquotes-pndef-no-nodj
    - ENV: fnquotes-pnquotes-no-django
    - ENV: fnquotes-pnquotes-no-nodj
before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
install:
  - mkdir -p ~/.pip
  - cp ci/pip.conf ~/.pip/pip.conf
  - pip install -U wheel setuptools
  - pip wheel tox virtualenv cookiecutter bumpversion
  - pip wheel pytest-capturelog pytest-cov pytest
  - pip wheel nose coverage
  - pip wheel cpp-coveralls
  - pip wheel jinja2 matrix
  - pip wheel docutils check-manifest flake8 readme-renderer pygments
  - pip install -I -U tox cookiecutter bumpversion
script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - ci/test.sh $ENV
notifications:
  email:
    on_success: never
    on_failure: always
addons:
  apt:
    packages: [libenchant-dev]
