language: python
python:
  - 3.5
sudo: false
cache:
  directories:
  - $HOME/.pip/wheels
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
  matrix:
    - ENV=fnaccents-pnaccents-no-py3doc-django
    - ENV=fnaccents-pnaccents-no-py3doc-nodj
    - ENV=fnaccents-pnaccents-no-rtd-django
    - ENV=fnaccents-pnaccents-no-rtd-nodj
    - ENV=fndef-pndef-argparse-py3doc-django
    - ENV=fndef-pndef-argparse-py3doc-nodj
    - ENV=fndef-pndef-argparse-rtd-django
    - ENV=fndef-pndef-argparse-rtd-nodj
    - ENV=fndef-pndef-click-py3doc-django
    - ENV=fndef-pndef-click-py3doc-nodj
    - ENV=fndef-pndef-click-rtd-django
    - ENV=fndef-pndef-click-rtd-nodj
    - ENV=fndef-pndef-no-py3doc-django
    - ENV=fndef-pndef-no-py3doc-nodj
    - ENV=fndef-pndef-no-rtd-django
    - ENV=fndef-pndef-no-rtd-nodj
    - ENV=fndef-pndef-plain-py3doc-django
    - ENV=fndef-pndef-plain-py3doc-nodj
    - ENV=fndef-pndef-plain-rtd-django
    - ENV=fndef-pndef-plain-rtd-nodj
    - ENV=fndef-pnquotes-no-py3doc-django
    - ENV=fndef-pnquotes-no-py3doc-nodj
    - ENV=fndef-pnquotes-no-rtd-django
    - ENV=fndef-pnquotes-no-rtd-nodj
    - ENV=fnquotes-pndef-no-py3doc-django
    - ENV=fnquotes-pndef-no-py3doc-nodj
    - ENV=fnquotes-pndef-no-rtd-django
    - ENV=fnquotes-pndef-no-rtd-nodj
    - ENV=fnquotes-pnquotes-no-py3doc-django
    - ENV=fnquotes-pnquotes-no-py3doc-nodj
    - ENV=fnquotes-pnquotes-no-rtd-django
    - ENV=fnquotes-pnquotes-no-rtd-nodj
before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
install:
  - mkdir -p ~/.pip
  - cp ci/pip.conf ~/.pip/pip.conf
  - pip install -U wheel setuptools
  - pip wheel tox virtualenv cookiecutter bumpversion
  - pip wheel pytest-capturelog pytest-cov pytest
  - pip wheel nose coverage
  - pip wheel cpp-coveralls
  - pip wheel jinja2 matrix
  - pip wheel docutils check-manifest flake8 readme-renderer pygments
  - pip install -I -U tox cookiecutter bumpversion
script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - ci/test.sh $ENV
notifications:
  email:
    on_success: never
    on_failure: always
