[tool.flit.metadata]
module="{{cookiecutter.package_name.replace('-','_')}}"
author="{{cookiecutter.full_name}}"
author-email="{{cookiecutter.email_name}}"
home-page="https://{{cookiecutter.provider}}.com/{{cookiecutter.repo_namespace}}/{{cookiecutter.repo_name}}"
requires=[]
requires-python="3"
description-file="README.rst"
classifiers=[
    # http://pypi.python.org/pypi?%3Aaction=list_classifiers
    "Intended Audience :: Developers",
    "License :: OSI Approved :: ISC License (ISCL)",
    "Development Status :: 3 - Alpha",
    "Operating System :: Unix",
    {% if cookiecutter.django|lower == "yes" -%}"Framework :: Django",{%- endif %}
    "Programming Language :: Python :: 3",
    'Topic :: Utilities',
]

[tool.flit.entrypoints."console_scripts"]
{{ cookiecutter.command_line_interface_bin_name }} = "{{ cookiecutter.package_name|replace('-', '_') }}.cli:main"
